import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BurguerMenu from "@/components/Search/BurguerMenu";
import Search from "@/components/Search/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Delicious Rebuild",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-[100vh] h-[100vh] pt-4">
      <body className={inter.className + ' bg-[#f3e5d8] flex flex-col w-[90vw] m-auto h-full'}>
          <BurguerMenu />
          <Search />
          {children}
      </body>
    </html>
  );
}
